from PyQt5.QtWidgets import QGroupBox, QLabel


class SetOrderTap:
    def __init__(self, ui_class, wc):
        self.ui = ui_class
        self.wc = wc
        self.set()

    def set(self):
        self.ui.sj_od_groupBoxxx_01 = QGroupBox(' 주식 매수주문의 방법 및 유형, 금지 사항 등을 설정한다.', self.ui.sod_tab)
        self.ui.sj_od_groupBoxxx_02 = QGroupBox(' 주식 매도주문의 방법 및 유형, 금지 사항 등을 설정한다.', self.ui.sod_tab)
        self.ui.sj_od_groupBoxxx_03 = QGroupBox(' 코인 매수주문의 방법 및 유형, 금지 사항 등을 설정한다.', self.ui.sod_tab)
        self.ui.sj_od_groupBoxxx_04 = QGroupBox(' 코인 매도주문의 방법 및 유형, 금지 사항 등을 설정한다.', self.ui.sod_tab)

        self.ui.sj_sodb_labellll_01 = QLabel('▣ 주문유형선택', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_01 = self.wc.setCheckBox('시장가', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_sodb_checkBox_02 = self.wc.setCheckBox('지정가', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='원하는 가격에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_sodb_checkBox_03 = self.wc.setCheckBox('최유리지정가', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매도1호가에 매도는 매수1호가에 원하는 수량만큼 주문하고 부족한 수량은 잔량 대기하는 방식')
        self.ui.sj_sodb_checkBox_04 = self.wc.setCheckBox('최우선지정가', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매수1호가에 매도는 매도1호가에 원하는 수량만큼 주문하는 방식, 체결이 안될 수도 있음')
        self.ui.sj_sodb_checkBox_05 = self.wc.setCheckBox('지정가IOC', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='원하는 가격에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_sodb_checkBox_06 = self.wc.setCheckBox('시장가IOC', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_sodb_checkBox_07 = self.wc.setCheckBox('최유리IOC', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매도1호가에 매도는 매수1호가에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_sodb_checkBox_08 = self.wc.setCheckBox('지정가FOK', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='원하는 가격에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_sodb_checkBox_09 = self.wc.setCheckBox('시장가FOK', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_sodb_checkBox_10 = self.wc.setCheckBox('최유리FOK', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_01, tip='매수는 매도호1가에 매도는 매수1호가에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_sodb_labellll_02 = QLabel('▣ 분할매수횟수               (1 : 분할매수X)', self.ui.sj_od_groupBoxxx_01)

        self.ui.sodb_checkbox_list1 = [
            self.ui.sj_sodb_checkBox_01, self.ui.sj_sodb_checkBox_02, self.ui.sj_sodb_checkBox_03,
            self.ui.sj_sodb_checkBox_04, self.ui.sj_sodb_checkBox_05, self.ui.sj_sodb_checkBox_06,
            self.ui.sj_sodb_checkBox_07, self.ui.sj_sodb_checkBox_08, self.ui.sj_sodb_checkBox_09,
            self.ui.sj_sodb_checkBox_10
        ]

        self.ui.sj_sodb_lineEdit_01 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_labellll_03 = QLabel('▣ 분할매수방법 : 복수선택불가능', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_11 = self.wc.setCheckBox('균등 분할', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_02, tip='종목당배팅금액을 분할횟수로 균등분할매수(예 0: 20., 1: 20., 2: 20., 3: 20., 4: 20.)')
        self.ui.sj_sodb_checkBox_12 = self.wc.setCheckBox('비율 감소', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_02, tip='다음 추가매수 시 이전 매수비율의 절반으로 매수(예 0: 51.61, 1: 25.81, 2: 12.90, 3: 6.45, 4: 3.23)')
        self.ui.sj_sodb_checkBox_13 = self.wc.setCheckBox('비율 증가', self.ui.sj_od_groupBoxxx_01, changed=self.ui.sbCheckboxChanged_02, tip='다음 추가매수 시 이전 매수비율의 두배로 매수(예 0: 3.23, 1: 6.45, 2: 12.90, 3: 25.81, 4: 51.61)')
        self.ui.sj_sodb_labellll_04 = QLabel('▣ 추가매수방법 : 복수선택가능', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_14 = self.wc.setCheckBox('매수시그널', self.ui.sj_od_groupBoxxx_01, tip='매수시그널을 통해서 추가매수')
        self.ui.sj_sodb_checkBox_15 = self.wc.setCheckBox('하방 고정 수익률 (-)', self.ui.sj_od_groupBoxxx_01, tip='잔고의 - 수익률를 기준으로 추가매수')
        self.ui.sj_sodb_lineEdit_02 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_16 = self.wc.setCheckBox('상방 고정 수익률', self.ui.sj_od_groupBoxxx_01, tip='잔고의 + 수익률를 기준으로 추가매수')
        self.ui.sj_sodb_lineEdit_03 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_27 = self.wc.setCheckBox('단계별 수익률로 변경', self.ui.sj_od_groupBoxxx_01, tip='마지막 매수시점의 현재가 기준 수익률로 추가매수')

        self.ui.sodb_checkbox_list2 = [self.ui.sj_sodb_checkBox_11, self.ui.sj_sodb_checkBox_12, self.ui.sj_sodb_checkBox_13]

        self.ui.sj_sodb_labellll_05 = QLabel('▣ 지정가유형 주문가격 기준가                                                        ▣ 시장가 유형 주문 시 호가범위 선택    매도                       호가', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_comboBox_01 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_01, items=['현재가', '매도1호가', '매수1호가'])
        self.ui.sj_sodb_comboBox_02 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_01, items=['5', '4', '3', '2', '1', '0', '-1', '-2', '-3', '-4', '-5'], tip='0은 기준가격이며 +- 호가단위로 선택하십시오.')
        self.ui.sj_sodb_comboBox_03 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_01, items=['1', '2', '3', '4', '5'])

        self.ui.sj_sodb_labellll_06 = QLabel('▣ 매수주문취소', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_17 = self.wc.setCheckBox('관심이탈', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_18 = self.wc.setCheckBox('매도시그널', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_19 = self.wc.setCheckBox('주문 후               초 경과', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_04 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)

        self.ui.sj_sodb_labellll_07 = QLabel('▣ 매수금지', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_20 = self.wc.setCheckBox('블랙리스트', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_21 = self.wc.setCheckBox('라운드피겨 ↑              호가 이내', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_05 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_22 = self.wc.setCheckBox('손절횟수               회 이상', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_06 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_23 = self.wc.setCheckBox('거래횟수               회 이상', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_07 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_24 = self.wc.setCheckBox('매수금지시간                    ~', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_08 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_09 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_25 = self.wc.setCheckBox('이전거래시간               초 이내', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_10 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_checkBox_26 = self.wc.setCheckBox('손절청산 후                 초 이내', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_11 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)

        self.ui.sj_sodb_labellll_08 = QLabel('▣ 매수정정          정정가능횟수                     (0: 매수정정X)         정정주문 조건 : 주문가격과 현재가의 차이가                     호가 이상               정정주문 시 정정가격 선택 현재가 (-)                     호가 (정정주문은 미체결수량에 대해서만 주문가격을 변경하여 주문한다)', self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_lineEdit_12 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_01)
        self.ui.sj_sodb_comboBox_04 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_01, items=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.ui.sj_sodb_comboBox_05 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_01, items=['0', '1', '2', '3', '4', '5'])

        # =============================================================================================================

        self.ui.sj_sods_labellll_01 = QLabel('▣ 주문유형선택', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_01 = self.wc.setCheckBox('시장가', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_sods_checkBox_02 = self.wc.setCheckBox('지정가', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='원하는 가격에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_sods_checkBox_03 = self.wc.setCheckBox('최유리지정가', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매도1호가에 매도는 매수1호가에 원하는 수량만큼 주문하고 부족한 수량은 잔량 대기하는 방식')
        self.ui.sj_sods_checkBox_04 = self.wc.setCheckBox('최우선지정가', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매수1호가에 매도는 매도1호가에 원하는 수량만큼 주문하는 방식, 체결이 안될 수도 있음')
        self.ui.sj_sods_checkBox_05 = self.wc.setCheckBox('지정가IOC', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='원하는 가격에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_sods_checkBox_06 = self.wc.setCheckBox('시장가IOC', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_sods_checkBox_07 = self.wc.setCheckBox('최유리IOC', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매도1호가에 매도는 매수1호가에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_sods_checkBox_08 = self.wc.setCheckBox('지정가FOK', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='원하는 가격에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_sods_checkBox_09 = self.wc.setCheckBox('시장가FOK', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_sods_checkBox_10 = self.wc.setCheckBox('최유리FOK', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_01, tip='매수는 매도호1가에 매도는 매수1호가에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_sods_labellll_02 = QLabel('▣ 분할매도횟수               (1 : 분할매도X)', self.ui.sj_od_groupBoxxx_02)

        self.ui.sods_checkbox_list1 = [
            self.ui.sj_sods_checkBox_01, self.ui.sj_sods_checkBox_02, self.ui.sj_sods_checkBox_03,
            self.ui.sj_sods_checkBox_04, self.ui.sj_sods_checkBox_05, self.ui.sj_sods_checkBox_06,
            self.ui.sj_sods_checkBox_07, self.ui.sj_sods_checkBox_08, self.ui.sj_sods_checkBox_09,
            self.ui.sj_sods_checkBox_10
        ]

        self.ui.sj_sods_lineEdit_01 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_labellll_03 = QLabel('▣ 분할매도방법 : 복수선택불가능', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_11 = self.wc.setCheckBox('균등 분할', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_02, tip='종목당배팅금액을 분할횟수로 균등분할매도(예 0: 20., 1: 20., 2: 20., 3: 20., 4: 20.)')
        self.ui.sj_sods_checkBox_12 = self.wc.setCheckBox('비율 감소', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_02, tip='다음 추가매도 시 이전 매도비율의 절반으로 매도(예 0: 51.61, 1: 25.81, 2: 12.90, 3: 6.45, 4: 3.23)')
        self.ui.sj_sods_checkBox_13 = self.wc.setCheckBox('비율 증가', self.ui.sj_od_groupBoxxx_02, changed=self.ui.ssCheckboxChanged_02, tip='다음 추가매도 시 이전 매도비율의 두배로 매도(예 0: 3.23, 1: 6.45, 2: 12.90, 3: 25.81, 4: 51.61)')
        self.ui.sj_sods_labellll_04 = QLabel('▣ 추가매도방법 : 복수선택가능', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_14 = self.wc.setCheckBox('매도시그널', self.ui.sj_od_groupBoxxx_02, tip='매도시그널을 통해서 추가매도')
        self.ui.sj_sods_checkBox_15 = self.wc.setCheckBox('하방 단계 수익률 (-)', self.ui.sj_od_groupBoxxx_02, tip='잔고의 마이너스 수익률를 기준으로 추가매도(0.5설정 시 예 0: -0.5, 1: -1.0, 2: -1.5, 3: -2.0, 4: -2.5)')
        self.ui.sj_sods_lineEdit_02 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_16 = self.wc.setCheckBox('상방 단계 수익률', self.ui.sj_od_groupBoxxx_02, tip='잔고의 플러스 수익률를 기준으로 추가매도(0.5설정 시 예 0: +0.5, 1: +1.0, 2: +1.5, 3: +2.0, 4: +2.5)')
        self.ui.sj_sods_lineEdit_03 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)

        self.ui.sods_checkbox_list2 = [self.ui.sj_sods_checkBox_11, self.ui.sj_sods_checkBox_12, self.ui.sj_sods_checkBox_13]

        self.ui.sj_sods_labellll_05 = QLabel('▣ 지정가유형 주문가격 기준가                                                        ▣ 시장가 유형 주문 시 호가범위 선택    매수                       호가', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_comboBox_01 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_02, items=['현재가', '매도1호가', '매수1호가'])
        self.ui.sj_sods_comboBox_02 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_02, items=['5', '4', '3', '2', '1', '0', '-1', '-2', '-3', '-4', '-5'], tip='0은 기준가격이며 +- 호가단위로 선택하십시오.')
        self.ui.sj_sods_comboBox_03 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_02, items=['1', '2', '3', '4', '5'])

        self.ui.sj_sods_labellll_06 = QLabel('▣ 매도주문취소', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_17 = self.wc.setCheckBox('관심진입', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_18 = self.wc.setCheckBox('매수시그널', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_19 = self.wc.setCheckBox('주문 후               초 경과', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_04 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_20 = self.wc.setCheckBox('손절전량청산 수익률 (-)', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_05 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_21 = self.wc.setCheckBox('손절전량청산 수익금 (-)', self.ui.sj_od_groupBoxxx_02, tip='만원 단위의 금액을 입력하십시오.')
        self.ui.sj_sods_lineEdit_06 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_labellll_07 = QLabel('▣ 매도금지', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_22 = self.wc.setCheckBox('분할매수횟수               회 이내', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_07 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_23 = self.wc.setCheckBox('라운드피겨 ↓              호가 이내', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_08 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_24 = self.wc.setCheckBox('매도금지시간                    ~', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_09 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_10 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_checkBox_25 = self.wc.setCheckBox('이전거래시간               초 이내', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_11 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)

        self.ui.sj_sods_labellll_08 = QLabel('▣ 매도정정          정정가능횟수                     (0: 매도정정X)         정정주문 조건 : 주문가격과 현재가의 차이가                     호가 이상               정정주문 시 정정가격 선택 현재가 (+)                     호가 (정정주문은 미체결수량에 대해서만 주문가격을 변경하여 주문한다)', self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_lineEdit_12 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_02)
        self.ui.sj_sods_comboBox_04 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_02, items=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.ui.sj_sods_comboBox_05 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_02, items=['0', '1', '2', '3', '4', '5'])

        # =============================================================================================================

        self.ui.sj_codb_labellll_01 = QLabel('▣ 주문유형선택', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_01 = self.wc.setCheckBox('시장가', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_codb_checkBox_02 = self.wc.setCheckBox('지정가', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_01, tip='원하는 가격에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_codb_checkBox_19 = self.wc.setCheckBox('지정가IOC', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_codb_checkBox_20 = self.wc.setCheckBox('지정가FOK', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_codb_labellll_02 = QLabel('▣ 분할매수횟수               (1 : 분할매수X)', self.ui.sj_od_groupBoxxx_03)

        self.ui.codb_checkbox_list1 = [self.ui.sj_codb_checkBox_01, self.ui.sj_codb_checkBox_02, self.ui.sj_codb_checkBox_19, self.ui.sj_codb_checkBox_20]

        self.ui.sj_codb_lineEdit_01 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_labellll_03 = QLabel('▣ 분할매수방법 : 복수선택불가능', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_03 = self.wc.setCheckBox('균등 분할', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_02, tip='종목당배팅금액을 분할횟수로 균등분할매수(예 0: 20., 1: 20., 2: 20., 3: 20., 4: 20.)')
        self.ui.sj_codb_checkBox_04 = self.wc.setCheckBox('비율 감소', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_02, tip='다음 추가매수 시 이전 매수비율의 절반으로 매수(예 0: 51.61, 1: 25.81, 2: 12.90, 3: 6.45, 4: 3.23)')
        self.ui.sj_codb_checkBox_05 = self.wc.setCheckBox('비율 증가', self.ui.sj_od_groupBoxxx_03, changed=self.ui.cbCheckboxChanged_02, tip='다음 추가매수 시 이전 매수비율의 두배로 매수(예 0: 3.23, 1: 6.45, 2: 12.90, 3: 25.81, 4: 51.61)')
        self.ui.sj_codb_labellll_04 = QLabel('▣ 추가매수방법 : 복수선택가능', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_06 = self.wc.setCheckBox('매수시그널', self.ui.sj_od_groupBoxxx_03, tip='매수시그널을 통해서 추가매수')
        self.ui.sj_codb_checkBox_07 = self.wc.setCheckBox('하방 고정 수익률 (-)', self.ui.sj_od_groupBoxxx_03, tip='잔고의 - 수익률를 기준으로 추가매수')
        self.ui.sj_codb_lineEdit_02 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_08 = self.wc.setCheckBox('상방 고정 수익률', self.ui.sj_od_groupBoxxx_03, tip='잔고의 + 수익률를 기준으로 추가매수')
        self.ui.sj_codb_lineEdit_03 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_27 = self.wc.setCheckBox('단계별 수익률로 변경', self.ui.sj_od_groupBoxxx_03, tip='마지막 매수시점의 현재가 기준 수익률로 추가매수')

        self.ui.codb_checkbox_list2 = [self.ui.sj_codb_checkBox_03, self.ui.sj_codb_checkBox_04, self.ui.sj_codb_checkBox_05]

        self.ui.sj_codb_labellll_05 = QLabel('▣ 지정가유형 주문가격 기준가                                                        ▣ 시장가 유형 주문 시 호가범위 선택    매도                       호가', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_comboBox_01 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_03, items=['현재가', '매도1호가', '매수1호가'])
        self.ui.sj_codb_comboBox_02 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_03, items=['5', '4', '3', '2', '1', '0', '-1', '-2', '-3', '-4', '-5'], tip='0은 기준가격이며 +- 호가단위로 선택하십시오.')
        self.ui.sj_codb_comboBox_03 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_03, items=['1', '2', '3', '4', '5'])

        self.ui.sj_codb_labellll_06 = QLabel('▣ 매수주문취소', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_09 = self.wc.setCheckBox('관심이탈', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_10 = self.wc.setCheckBox('매도시그널', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_11 = self.wc.setCheckBox('주문 후               초 경과', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_04 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)

        self.ui.sj_codb_labellll_07 = QLabel('▣ 매수금지', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_12 = self.wc.setCheckBox('블랙리스트', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_13 = self.wc.setCheckBox('1코인 200원 이하', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_14 = self.wc.setCheckBox('손절횟수               회 이상', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_05 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_15 = self.wc.setCheckBox('거래횟수               회 이상', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_06 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_16 = self.wc.setCheckBox('매수금지시간                    ~', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_07 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_08 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_17 = self.wc.setCheckBox('이전거래시간               초 이내', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_09 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_checkBox_18 = self.wc.setCheckBox('손절청산 후                 초 이내', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_10 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)

        self.ui.sj_codb_labellll_08 = QLabel('▣ 매수정정          정정가능횟수                     (0: 매수정정X)         정정주문 조건 : 주문가격과 현재가의 차이가                     호가 이상               정정주문 시 정정가격 선택 현재가 (-)                     호가 (정정주문은 미체결수량에 대해서만 주문가격을 변경하여 주문한다)', self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_lineEdit_11 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_03)
        self.ui.sj_codb_comboBox_04 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_03, items=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.ui.sj_codb_comboBox_05 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_03, items=['0', '1', '2', '3', '4', '5'])

        # =============================================================================================================

        self.ui.sj_cods_labellll_01 = QLabel('▣ 주문유형선택', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_01 = self.wc.setCheckBox('시장가', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_cods_checkBox_02 = self.wc.setCheckBox('지정가', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_01, tip='원하는 가격에 원하는 수량만큼 주문하는 방식')
        self.ui.sj_cods_checkBox_19 = self.wc.setCheckBox('지정가IOC', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량만큼 주문하고 미체결수량은 취소하는 방식')
        self.ui.sj_cods_checkBox_20 = self.wc.setCheckBox('지정가FOK', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_01, tip='매수는 매도호가에 매도는 매수호가에 원하는 수량이 있을 경우 주문하고 없을 경우 취소하는 방식')
        self.ui.sj_cods_labellll_02 = QLabel('▣ 분할매도횟수               (1 : 분할매도X)', self.ui.sj_od_groupBoxxx_04)

        self.ui.cods_checkbox_list1 = [self.ui.sj_cods_checkBox_01, self.ui.sj_cods_checkBox_02, self.ui.sj_cods_checkBox_19, self.ui.sj_cods_checkBox_20]

        self.ui.sj_cods_lineEdit_01 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_labellll_03 = QLabel('▣ 분할매도방법 : 복수선택불가능', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_03 = self.wc.setCheckBox('균등 분할', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_02, tip='종목당배팅금액을 분할횟수로 균등분할매도(예 0: 20., 1: 20., 2: 20., 3: 20., 4: 20.)')
        self.ui.sj_cods_checkBox_04 = self.wc.setCheckBox('비율 감소', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_02, tip='다음 추가매도 시 이전 매도비율의 절반으로 매도(예 0: 51.61, 1: 25.81, 2: 12.90, 3: 6.45, 4: 3.23)')
        self.ui.sj_cods_checkBox_05 = self.wc.setCheckBox('비율 증가', self.ui.sj_od_groupBoxxx_04, changed=self.ui.csCheckboxChanged_02, tip='다음 추가매도 시 이전 매도비율의 두배로 매도(예 0: 3.23, 1: 6.45, 2: 12.90, 3: 25.81, 4: 51.61)')
        self.ui.sj_cods_labellll_04 = QLabel('▣ 추가매도방법 : 복수선택가능', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_06 = self.wc.setCheckBox('매도시그널', self.ui.sj_od_groupBoxxx_04, tip='매도시그널을 통해서 추가매도')
        self.ui.sj_cods_checkBox_07 = self.wc.setCheckBox('하방 단계 수익률 (-)', self.ui.sj_od_groupBoxxx_04, tip='잔고의 마이너스 수익률를 기준으로 추가매도(0.5설정 시 예 0: -0.5, 1: -1.0, 2: -1.5, 3: -2.0, 4: -2.5)')
        self.ui.sj_cods_lineEdit_02 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_08 = self.wc.setCheckBox('상방 단계 수익률', self.ui.sj_od_groupBoxxx_04, tip='잔고의 플러스 수익률를 기준으로 추가매도(0.5설정 시 예 0: +0.5, 1: +1.0, 2: +1.5, 3: +2.0, 4: +2.5)')
        self.ui.sj_cods_lineEdit_03 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)

        self.ui.cods_checkbox_list2 = [self.ui.sj_cods_checkBox_03, self.ui.sj_cods_checkBox_04, self.ui.sj_cods_checkBox_05]

        self.ui.sj_cods_labellll_05 = QLabel('▣ 지정가유형 주문가격 기준가                                                        ▣ 시장가 유형 주문 시 호가범위 선택    매수                       호가', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_comboBox_01 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_04, items=['현재가', '매도1호가', '매수1호가'])
        self.ui.sj_cods_comboBox_02 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_04, items=['5', '4', '3', '2', '1', '0', '-1', '-2', '-3', '-4', '-5'], tip='0은 기준가격이며 +- 호가단위로 선택하십시오.')
        self.ui.sj_cods_comboBox_03 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_04, items=['1', '2', '3', '4', '5'])

        self.ui.sj_cods_labellll_06 = QLabel('▣ 매도주문취소', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_09 = self.wc.setCheckBox('관심진입', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_10 = self.wc.setCheckBox('매수시그널', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_11 = self.wc.setCheckBox('주문 후               초 경과', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_04 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_12 = self.wc.setCheckBox('손절전량청산 수익률 (-)', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_05 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_13 = self.wc.setCheckBox('손절전량청산 수익금 (-)', self.ui.sj_od_groupBoxxx_04, tip='만원 또는 USDT 단위의 금액을 입력하십시오.')
        self.ui.sj_cods_lineEdit_06 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_labellll_07 = QLabel('▣ 매도금지', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_14 = self.wc.setCheckBox('분할매수횟수               회 이내', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_07 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_15 = self.wc.setCheckBox('매도금지시간                    ~', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_08 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_09 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_checkBox_16 = self.wc.setCheckBox('이전거래시간               초 이내', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_10 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)

        self.ui.sj_cods_labellll_08 = QLabel('▣ 매도정정          정정가능횟수                     (0: 매도정정X)         정정주문 조건 : 주문가격과 현재가의 차이가                     호가 이상               정정주문 시 정정가격 선택 현재가 (+)                     호가 (정정주문은 미체결수량에 대해서만 주문가격을 변경하여 주문한다)', self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_lineEdit_11 = self.wc.setLineedit(self.ui.sj_od_groupBoxxx_04)
        self.ui.sj_cods_comboBox_04 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_04, items=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.ui.sj_cods_comboBox_05 = self.wc.setCombobox(self.ui.sj_od_groupBoxxx_04, items=['0', '1', '2', '3', '4', '5'])

        # =============================================================================================================

        self.ui.sj_load_Button_09 = self.wc.setPushbutton('불러오기', box=self.ui.sj_od_groupBoxxx_01, click=self.ui.sjButtonClicked_19)
        self.ui.sj_load_Button_10 = self.wc.setPushbutton('불러오기', box=self.ui.sj_od_groupBoxxx_02, click=self.ui.sjButtonClicked_20)
        self.ui.sj_load_Button_11 = self.wc.setPushbutton('불러오기', box=self.ui.sj_od_groupBoxxx_03, click=self.ui.sjButtonClicked_21)
        self.ui.sj_load_Button_12 = self.wc.setPushbutton('불러오기', box=self.ui.sj_od_groupBoxxx_04, click=self.ui.sjButtonClicked_22)

        self.ui.sj_save_Button_09 = self.wc.setPushbutton('저장하기', box=self.ui.sj_od_groupBoxxx_01, click=self.ui.sjButtonClicked_23)
        self.ui.sj_save_Button_10 = self.wc.setPushbutton('저장하기', box=self.ui.sj_od_groupBoxxx_02, click=self.ui.sjButtonClicked_24)
        self.ui.sj_save_Button_11 = self.wc.setPushbutton('저장하기', box=self.ui.sj_od_groupBoxxx_03, click=self.ui.sjButtonClicked_25)
        self.ui.sj_save_Button_12 = self.wc.setPushbutton('저장하기', box=self.ui.sj_od_groupBoxxx_04, click=self.ui.sjButtonClicked_26)

        self.ui.sj_od_groupBoxxx_01.setGeometry(5, 5, 1326, 155)
        self.ui.sj_od_groupBoxxx_02.setGeometry(5, 170, 1326, 155)
        self.ui.sj_od_groupBoxxx_03.setGeometry(5, 335, 1326, 155)
        self.ui.sj_od_groupBoxxx_04.setGeometry(5, 500, 1326, 155)

        self.ui.sj_sodb_labellll_01.setGeometry(10, 25, 80, 20)
        self.ui.sj_sodb_checkBox_01.setGeometry(100, 25, 55, 20)
        self.ui.sj_sodb_checkBox_02.setGeometry(165, 25, 55, 20)
        self.ui.sj_sodb_checkBox_03.setGeometry(230, 25, 90, 20)
        self.ui.sj_sodb_checkBox_04.setGeometry(330, 25, 90, 20)
        self.ui.sj_sodb_checkBox_05.setGeometry(430, 25, 80, 20)
        self.ui.sj_sodb_checkBox_06.setGeometry(520, 25, 80, 20)
        self.ui.sj_sodb_checkBox_07.setGeometry(610, 25, 80, 20)
        self.ui.sj_sodb_checkBox_08.setGeometry(700, 25, 80, 20)
        self.ui.sj_sodb_checkBox_09.setGeometry(790, 25, 80, 20)
        self.ui.sj_sodb_checkBox_10.setGeometry(880, 25, 80, 20)
        self.ui.sj_sodb_labellll_02.setGeometry(970, 25, 220, 20)
        self.ui.sj_sodb_lineEdit_01.setGeometry(1060, 25, 30, 20)

        self.ui.sj_sodb_labellll_03.setGeometry(10, 50, 200, 20)
        self.ui.sj_sodb_checkBox_11.setGeometry(230, 50, 80, 20)
        self.ui.sj_sodb_checkBox_12.setGeometry(330, 50, 80, 20)
        self.ui.sj_sodb_checkBox_13.setGeometry(430, 50, 80, 20)
        self.ui.sj_sodb_labellll_04.setGeometry(520, 50, 200, 20)
        self.ui.sj_sodb_checkBox_14.setGeometry(700, 50, 80, 20)
        self.ui.sj_sodb_checkBox_15.setGeometry(790, 50, 170, 20)
        self.ui.sj_sodb_lineEdit_02.setGeometry(910, 50, 40, 20)
        self.ui.sj_sodb_checkBox_16.setGeometry(970, 50, 170, 20)
        self.ui.sj_sodb_lineEdit_03.setGeometry(1080, 50, 40, 20)
        self.ui.sj_sodb_checkBox_27.setGeometry(1140, 50, 150, 20)

        self.ui.sj_sodb_labellll_05.setGeometry(10, 75, 680, 20)
        self.ui.sj_sodb_comboBox_01.setGeometry(170, 75, 80, 20)
        self.ui.sj_sodb_comboBox_02.setGeometry(260, 75, 50, 20)
        self.ui.sj_sodb_comboBox_03.setGeometry(560, 75, 50, 20)
        self.ui.sj_sodb_labellll_06.setGeometry(700, 75, 80, 20)
        self.ui.sj_sodb_checkBox_17.setGeometry(790, 75, 80, 20)
        self.ui.sj_sodb_checkBox_18.setGeometry(880, 75, 80, 20)
        self.ui.sj_sodb_checkBox_19.setGeometry(970, 75, 150, 20)
        self.ui.sj_sodb_lineEdit_04.setGeometry(1035, 75, 30, 20)

        self.ui.sj_sodb_labellll_07.setGeometry(10, 100, 80, 20)
        self.ui.sj_sodb_checkBox_20.setGeometry(100, 100, 80, 20)
        self.ui.sj_sodb_checkBox_21.setGeometry(190, 100, 180, 20)
        self.ui.sj_sodb_lineEdit_05.setGeometry(280, 100, 30, 20)
        self.ui.sj_sodb_checkBox_22.setGeometry(375, 100, 150, 20)
        self.ui.sj_sodb_lineEdit_06.setGeometry(445, 100, 30, 20)
        self.ui.sj_sodb_checkBox_23.setGeometry(535, 100, 150, 20)
        self.ui.sj_sodb_lineEdit_07.setGeometry(605, 100, 30, 20)
        self.ui.sj_sodb_checkBox_24.setGeometry(700, 100, 200, 20)
        self.ui.sj_sodb_lineEdit_08.setGeometry(790, 100, 50, 20)
        self.ui.sj_sodb_lineEdit_09.setGeometry(860, 100, 50, 20)
        self.ui.sj_sodb_checkBox_25.setGeometry(930, 100, 170, 20)
        self.ui.sj_sodb_lineEdit_10.setGeometry(1025, 100, 30, 20)
        self.ui.sj_sodb_checkBox_26.setGeometry(1110, 100, 170, 20)
        self.ui.sj_sodb_lineEdit_11.setGeometry(1195, 100, 40, 20)

        self.ui.sj_sodb_labellll_08.setGeometry(10, 125, 1350, 20)
        self.ui.sj_sodb_lineEdit_12.setGeometry(190, 125, 30, 20)
        self.ui.sj_sodb_comboBox_04.setGeometry(552, 125, 50, 20)
        self.ui.sj_sodb_comboBox_05.setGeometry(890, 125, 50, 20)

        self.ui.sj_sods_labellll_01.setGeometry(10, 25, 80, 20)
        self.ui.sj_sods_checkBox_01.setGeometry(100, 25, 55, 20)
        self.ui.sj_sods_checkBox_02.setGeometry(165, 25, 55, 20)
        self.ui.sj_sods_checkBox_03.setGeometry(230, 25, 90, 20)
        self.ui.sj_sods_checkBox_04.setGeometry(330, 25, 90, 20)
        self.ui.sj_sods_checkBox_05.setGeometry(430, 25, 80, 20)
        self.ui.sj_sods_checkBox_06.setGeometry(520, 25, 80, 20)
        self.ui.sj_sods_checkBox_07.setGeometry(610, 25, 80, 20)
        self.ui.sj_sods_checkBox_08.setGeometry(700, 25, 80, 20)
        self.ui.sj_sods_checkBox_09.setGeometry(790, 25, 80, 20)
        self.ui.sj_sods_checkBox_10.setGeometry(880, 25, 80, 20)
        self.ui.sj_sods_labellll_02.setGeometry(970, 25, 220, 20)
        self.ui.sj_sods_lineEdit_01.setGeometry(1060, 25, 30, 20)

        self.ui.sj_sods_labellll_03.setGeometry(10, 50, 200, 20)
        self.ui.sj_sods_checkBox_11.setGeometry(230, 50, 100, 20)
        self.ui.sj_sods_checkBox_12.setGeometry(330, 50, 100, 20)
        self.ui.sj_sods_checkBox_13.setGeometry(430, 50, 100, 20)
        self.ui.sj_sods_labellll_04.setGeometry(520, 50, 200, 20)
        self.ui.sj_sods_checkBox_14.setGeometry(700, 50, 80, 20)
        self.ui.sj_sods_checkBox_15.setGeometry(790, 50, 170, 20)
        self.ui.sj_sods_lineEdit_02.setGeometry(910, 50, 40, 20)
        self.ui.sj_sods_checkBox_16.setGeometry(970, 50, 170, 20)
        self.ui.sj_sods_lineEdit_03.setGeometry(1080, 50, 40, 20)

        self.ui.sj_sods_labellll_05.setGeometry(10, 75, 680, 20)
        self.ui.sj_sods_comboBox_01.setGeometry(170, 75, 80, 20)
        self.ui.sj_sods_comboBox_02.setGeometry(260, 75, 50, 20)
        self.ui.sj_sods_comboBox_03.setGeometry(560, 75, 50, 20)
        self.ui.sj_sods_labellll_06.setGeometry(700, 75, 80, 20)
        self.ui.sj_sods_checkBox_17.setGeometry(790, 75, 80, 20)
        self.ui.sj_sods_checkBox_18.setGeometry(880, 75, 80, 20)
        self.ui.sj_sods_checkBox_19.setGeometry(970, 75, 150, 20)
        self.ui.sj_sods_lineEdit_04.setGeometry(1035, 75, 30, 20)

        self.ui.sj_sods_checkBox_20.setGeometry(10, 100, 200, 20)
        self.ui.sj_sods_lineEdit_05.setGeometry(150, 100, 40, 20)
        self.ui.sj_sods_checkBox_21.setGeometry(230, 100, 200, 20)
        self.ui.sj_sods_lineEdit_06.setGeometry(370, 100, 40, 20)
        self.ui.sj_sods_labellll_07.setGeometry(430, 100, 80, 20)
        self.ui.sj_sods_checkBox_22.setGeometry(520, 100, 180, 20)
        self.ui.sj_sods_lineEdit_07.setGeometry(615, 100, 30, 20)
        self.ui.sj_sods_checkBox_23.setGeometry(700, 100, 180, 20)
        self.ui.sj_sods_lineEdit_08.setGeometry(790, 100, 30, 20)
        self.ui.sj_sods_checkBox_24.setGeometry(880, 100, 200, 20)
        self.ui.sj_sods_lineEdit_09.setGeometry(970, 100, 50, 20)
        self.ui.sj_sods_lineEdit_10.setGeometry(1040, 100, 50, 20)
        self.ui.sj_sods_checkBox_25.setGeometry(1110, 100, 170, 20)
        self.ui.sj_sods_lineEdit_11.setGeometry(1205, 100, 30, 20)

        self.ui.sj_sods_labellll_08.setGeometry(10, 125, 1350, 20)
        self.ui.sj_sods_lineEdit_12.setGeometry(190, 125, 30, 20)
        self.ui.sj_sods_comboBox_04.setGeometry(552, 125, 50, 20)
        self.ui.sj_sods_comboBox_05.setGeometry(890, 125, 50, 20)

        self.ui.sj_codb_labellll_01.setGeometry(10, 25, 80, 20)
        self.ui.sj_codb_checkBox_01.setGeometry(100, 25, 55, 20)
        self.ui.sj_codb_checkBox_02.setGeometry(165, 25, 55, 20)
        self.ui.sj_codb_checkBox_19.setGeometry(230, 25, 80, 20)
        self.ui.sj_codb_checkBox_20.setGeometry(320, 25, 80, 20)
        self.ui.sj_codb_labellll_02.setGeometry(410, 25, 220, 20)
        self.ui.sj_codb_lineEdit_01.setGeometry(500, 25, 30, 20)

        self.ui.sj_codb_labellll_03.setGeometry(10, 50, 200, 20)
        self.ui.sj_codb_checkBox_03.setGeometry(230, 50, 80, 20)
        self.ui.sj_codb_checkBox_04.setGeometry(330, 50, 80, 20)
        self.ui.sj_codb_checkBox_05.setGeometry(430, 50, 80, 20)
        self.ui.sj_codb_labellll_04.setGeometry(520, 50, 200, 20)
        self.ui.sj_codb_checkBox_06.setGeometry(700, 50, 80, 20)
        self.ui.sj_codb_checkBox_07.setGeometry(790, 50, 170, 20)
        self.ui.sj_codb_lineEdit_02.setGeometry(910, 50, 40, 20)
        self.ui.sj_codb_checkBox_08.setGeometry(970, 50, 170, 20)
        self.ui.sj_codb_lineEdit_03.setGeometry(1080, 50, 40, 20)
        self.ui.sj_codb_checkBox_27.setGeometry(1140, 50, 150, 20)

        self.ui.sj_codb_labellll_05.setGeometry(10, 75, 680, 20)
        self.ui.sj_codb_comboBox_01.setGeometry(170, 75, 80, 20)
        self.ui.sj_codb_comboBox_02.setGeometry(260, 75, 50, 20)
        self.ui.sj_codb_comboBox_03.setGeometry(560, 75, 50, 20)
        self.ui.sj_codb_labellll_06.setGeometry(700, 75, 80, 20)
        self.ui.sj_codb_checkBox_09.setGeometry(790, 75, 80, 20)
        self.ui.sj_codb_checkBox_10.setGeometry(880, 75, 80, 20)
        self.ui.sj_codb_checkBox_11.setGeometry(970, 75, 150, 20)
        self.ui.sj_codb_lineEdit_04.setGeometry(1035, 75, 30, 20)

        self.ui.sj_codb_labellll_07.setGeometry(10, 100, 80, 20)
        self.ui.sj_codb_checkBox_12.setGeometry(100, 100, 80, 20)
        self.ui.sj_codb_checkBox_13.setGeometry(190, 100, 150, 20)
        self.ui.sj_codb_checkBox_14.setGeometry(330, 100, 150, 20)
        self.ui.sj_codb_lineEdit_05.setGeometry(400, 100, 30, 20)
        self.ui.sj_codb_checkBox_15.setGeometry(520, 100, 200, 20)
        self.ui.sj_codb_lineEdit_06.setGeometry(590, 100, 30, 20)
        self.ui.sj_codb_checkBox_16.setGeometry(700, 100, 200, 20)
        self.ui.sj_codb_lineEdit_07.setGeometry(790, 100, 50, 20)
        self.ui.sj_codb_lineEdit_08.setGeometry(860, 100, 50, 20)
        self.ui.sj_codb_checkBox_17.setGeometry(930, 100, 200, 20)
        self.ui.sj_codb_lineEdit_09.setGeometry(1025, 100, 30, 20)
        self.ui.sj_codb_checkBox_18.setGeometry(1110, 100, 170, 20)
        self.ui.sj_codb_lineEdit_10.setGeometry(1195, 100, 40, 20)

        self.ui.sj_codb_labellll_08.setGeometry(10, 125, 1350, 20)
        self.ui.sj_codb_lineEdit_11.setGeometry(190, 125, 30, 20)
        self.ui.sj_codb_comboBox_04.setGeometry(552, 125, 50, 20)
        self.ui.sj_codb_comboBox_05.setGeometry(890, 125, 50, 20)

        self.ui.sj_cods_labellll_01.setGeometry(10, 25, 80, 20)
        self.ui.sj_cods_checkBox_01.setGeometry(100, 25, 55, 20)
        self.ui.sj_cods_checkBox_02.setGeometry(165, 25, 55, 20)
        self.ui.sj_cods_checkBox_19.setGeometry(230, 25, 80, 20)
        self.ui.sj_cods_checkBox_20.setGeometry(320, 25, 80, 20)
        self.ui.sj_cods_labellll_02.setGeometry(410, 25, 220, 20)
        self.ui.sj_cods_lineEdit_01.setGeometry(500, 25, 30, 20)

        self.ui.sj_cods_labellll_03.setGeometry(10, 50, 200, 20)
        self.ui.sj_cods_checkBox_03.setGeometry(230, 50, 80, 20)
        self.ui.sj_cods_checkBox_04.setGeometry(330, 50, 80, 20)
        self.ui.sj_cods_checkBox_05.setGeometry(430, 50, 80, 20)
        self.ui.sj_cods_labellll_04.setGeometry(520, 50, 200, 20)
        self.ui.sj_cods_checkBox_06.setGeometry(700, 50, 80, 20)
        self.ui.sj_cods_checkBox_07.setGeometry(790, 50, 170, 20)
        self.ui.sj_cods_lineEdit_02.setGeometry(910, 50, 40, 20)
        self.ui.sj_cods_checkBox_08.setGeometry(970, 50, 170, 20)
        self.ui.sj_cods_lineEdit_03.setGeometry(1080, 50, 40, 20)

        self.ui.sj_cods_labellll_05.setGeometry(10, 75, 680, 20)
        self.ui.sj_cods_comboBox_01.setGeometry(170, 75, 80, 20)
        self.ui.sj_cods_comboBox_02.setGeometry(260, 75, 50, 20)
        self.ui.sj_cods_comboBox_03.setGeometry(560, 75, 50, 20)
        self.ui.sj_cods_labellll_06.setGeometry(700, 75, 80, 20)
        self.ui.sj_cods_checkBox_09.setGeometry(790, 75, 80, 20)
        self.ui.sj_cods_checkBox_10.setGeometry(880, 75, 80, 20)
        self.ui.sj_cods_checkBox_11.setGeometry(970, 75, 150, 20)
        self.ui.sj_cods_lineEdit_04.setGeometry(1035, 75, 30, 20)

        self.ui.sj_cods_checkBox_12.setGeometry(10, 100, 200, 20)
        self.ui.sj_cods_lineEdit_05.setGeometry(150, 100, 40, 20)
        self.ui.sj_cods_checkBox_13.setGeometry(230, 100, 200, 20)
        self.ui.sj_cods_lineEdit_06.setGeometry(370, 100, 40, 20)
        self.ui.sj_cods_labellll_07.setGeometry(430, 100, 80, 20)
        self.ui.sj_cods_checkBox_14.setGeometry(520, 100, 200, 20)
        self.ui.sj_cods_lineEdit_07.setGeometry(615, 100, 30, 20)
        self.ui.sj_cods_checkBox_15.setGeometry(880, 100, 200, 20)
        self.ui.sj_cods_lineEdit_08.setGeometry(970, 100, 50, 20)
        self.ui.sj_cods_lineEdit_09.setGeometry(1040, 100, 50, 20)
        self.ui.sj_cods_checkBox_16.setGeometry(1110, 100, 170, 20)
        self.ui.sj_cods_lineEdit_10.setGeometry(1205, 100, 30, 20)

        self.ui.sj_cods_labellll_08.setGeometry(10, 125, 1350, 20)
        self.ui.sj_cods_lineEdit_11.setGeometry(190, 125, 30, 20)
        self.ui.sj_cods_comboBox_04.setGeometry(552, 125, 50, 20)
        self.ui.sj_cods_comboBox_05.setGeometry(890, 125, 50, 20)

        self.ui.sj_load_Button_09.setGeometry(1175, 25, 70, 20)
        self.ui.sj_load_Button_10.setGeometry(1175, 25, 70, 20)
        self.ui.sj_load_Button_11.setGeometry(1175, 25, 70, 20)
        self.ui.sj_load_Button_12.setGeometry(1175, 25, 70, 20)

        self.ui.sj_save_Button_09.setGeometry(1250, 25, 70, 20)
        self.ui.sj_save_Button_10.setGeometry(1250, 25, 70, 20)
        self.ui.sj_save_Button_11.setGeometry(1250, 25, 70, 20)
        self.ui.sj_save_Button_12.setGeometry(1250, 25, 70, 20)
